name: Terraform Provisioning

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.6.6

    # - name: Configure AWS credentials
    #   run: |
    #     mkdir -p ~/.aws
    #     echo -e "[default]\naws_access_key_id=${{ secrets.AWS_ACCESS_KEY_ID }}\naws_secret_access_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}" > ~/.aws/credentials

    - name: Initialize Terraform
      run: terraform init

    - name: Format Terraform files
      run: terraform fmt

    - name: Plan Terraform changes
      run: terraform plan -out tfplan

    - name: Apply Terraform changes
      run: terraform apply --auto-approve tfplan
